import type { Tag, Track } from "@/music/types";

export const SAMPLE_TAGS: Tag[] = [
  { id: "tag-1", labels: { ja: "タグ1", en: "Tag 1" }, group: "Genre" },
  { id: "tag-2", labels: { ja: "タグ2", en: "Tag 2" }, group: "Genre" },
  { id: "tag-3", labels: { ja: "タグ3", en: "Tag 3" }, group: "Genre" },
  { id: "tag-4", labels: { ja: "タグ4", en: "Tag 4" }, group: "Genre" },
  { id: "tag-5", labels: { ja: "タグ5", en: "Tag 5" }, group: "Genre" },
  { id: "tag-6", labels: { ja: "タグ6", en: "Tag 6" }, group: "Genre" },
  { id: "tag-7", labels: { ja: "タグ7", en: "Tag 7" }, group: "Genre" },
  { id: "tag-8", labels: { ja: "タグ8", en: "Tag 8" }, group: "Genre" },
  { id: "tag-9", labels: { ja: "タグ9", en: "Tag 9" }, group: "Genre" },
  { id: "tag-10", labels: { ja: "タグ10", en: "Tag 10" }, group: "Genre" },
  { id: "tag-11", labels: { ja: "タグ11", en: "Tag 11" }, group: "Genre" },
  { id: "tag-12", labels: { ja: "タグ12", en: "Tag 12" }, group: "Genre" },
  { id: "tag-13", labels: { ja: "タグ13", en: "Tag 13" }, group: "Genre" },
  { id: "tag-14", labels: { ja: "タグ14", en: "Tag 14" }, group: "Genre" },
  { id: "tag-15", labels: { ja: "タグ15", en: "Tag 15" }, group: "Genre" },
];

export const SAMPLE_TRACKS: Track[] = [
  {
    id: "sample-1",
    slug: "sample-1",
    title: "サンプル音源1",
    artist: "Music Library",
    albumArtSrc: "/music/art/aurora-drift.svg",
    audioSrc: "/music/audio/aurora-drift.wav",
    description: "This is a sample track for template demonstration.",
    bpm: 78,
    tags: ["tag-1"],
    license: {
      licenseId: "sample",
      requiresAgreement: false,
      note: "Template sample license note. Replace this with your own policy.",
      clearanceUrl: "https://example.com",
    },
    downloads: [
      {
        downloadId: "full",
        variant: "full",
        label: "Full",
        format: "wav",
        directUrl: "/music/audio/aurora-drift.wav",
      },
    ],
  },
  {
    id: "sample-2",
    slug: "sample-2",
    title: "サンプル音源2",
    artist: "Music Library",
    albumArtSrc: "/music/art/midnight-commute.svg",
    audioSrc: "/music/audio/midnight-commute.wav",
    description: "This is a sample track for template demonstration.",
    bpm: 96,
    tags: ["tag-2"],
    license: {
      licenseId: "sample",
      requiresAgreement: true,
      note: "Template sample license note. Replace this with your own policy.",
      clearanceUrl: "https://example.com",
    },
    downloads: [
      {
        downloadId: "full",
        variant: "full",
        label: "Full",
        format: "wav",
        directUrl: "/music/audio/midnight-commute.wav",
      },
    ],
  },
  {
    id: "sample-3",
    slug: "sample-3",
    title: "サンプル音源3",
    artist: "Music Library",
    albumArtSrc: "/music/art/paper-skies.svg",
    audioSrc: "/music/audio/paper-skies.wav",
    description: "This is a sample track for template demonstration.",
    bpm: 90,
    tags: ["tag-3"],
    license: {
      licenseId: "sample",
      requiresAgreement: false,
      note: "Template sample license note. Replace this with your own policy.",
      clearanceUrl: "https://example.com",
    },
    downloads: [
      {
        downloadId: "full",
        variant: "full",
        label: "Full",
        format: "wav",
        directUrl: "/music/audio/paper-skies.wav",
      },
    ],
  },
  {
    id: "sample-4",
    slug: "sample-4",
    title: "サンプル音源4",
    artist: "Music Library",
    albumArtSrc: "/music/art/neon-rain.svg",
    audioSrc: "/music/audio/neon-rain.wav",
    description: "This is a sample track for template demonstration.",
    bpm: 110,
    tags: ["tag-4"],
    license: {
      licenseId: "sample",
      requiresAgreement: true,
      note: "Template sample license note. Replace this with your own policy.",
      clearanceUrl: "https://example.com",
    },
    downloads: [
      {
        downloadId: "full",
        variant: "full",
        label: "Full",
        format: "wav",
        directUrl: "/music/audio/neon-rain.wav",
      },
    ],
  },
  {
    id: "sample-5",
    slug: "sample-5",
    title: "サンプル音源5",
    artist: "Music Library",
    albumArtSrc: "/music/art/calm-current.svg",
    audioSrc: "/music/audio/calm-current.wav",
    description: "This is a sample track for template demonstration.",
    bpm: 72,
    tags: ["tag-5"],
    license: {
      licenseId: "sample",
      requiresAgreement: false,
      note: "Template sample license note. Replace this with your own policy.",
      clearanceUrl: "https://example.com",
    },
    downloads: [
      {
        downloadId: "full",
        variant: "full",
        label: "Full",
        format: "wav",
        directUrl: "/music/audio/calm-current.wav",
      },
    ],
  },
  {
    id: "sample-6",
    slug: "sample-6",
    title: "サンプル音源6",
    artist: "Music Library",
    albumArtSrc: "/music/art/silver-steps.svg",
    audioSrc: "/music/audio/silver-steps.wav",
    description: "This is a sample track for template demonstration.",
    bpm: 100,
    tags: ["tag-6"],
    license: {
      licenseId: "sample",
      requiresAgreement: true,
      note: "Template sample license note. Replace this with your own policy.",
      clearanceUrl: "https://example.com",
    },
    downloads: [
      {
        downloadId: "full",
        variant: "full",
        label: "Full",
        format: "wav",
        directUrl: "/music/audio/silver-steps.wav",
      },
    ],
  },
  {
    id: "sample-7",
    slug: "sample-7",
    title: "サンプル音源7",
    artist: "Music Library",
    albumArtSrc: "/music/art/aurora-drift.svg",
    audioSrc: "/music/audio/aurora-drift.wav",
    description: "This is a sample track for template demonstration.",
    bpm: 82,
    tags: ["tag-7"],
    license: {
      licenseId: "sample",
      requiresAgreement: false,
      note: "Template sample license note. Replace this with your own policy.",
      clearanceUrl: "https://example.com",
    },
    downloads: [
      {
        downloadId: "full",
        variant: "full",
        label: "Full",
        format: "wav",
        directUrl: "/music/audio/aurora-drift.wav",
      },
    ],
  },
  {
    id: "sample-8",
    slug: "sample-8",
    title: "サンプル音源8",
    artist: "Music Library",
    albumArtSrc: "/music/art/midnight-commute.svg",
    audioSrc: "/music/audio/midnight-commute.wav",
    description: "This is a sample track for template demonstration.",
    bpm: 88,
    tags: ["tag-8"],
    license: {
      licenseId: "sample",
      requiresAgreement: true,
      note: "Template sample license note. Replace this with your own policy.",
      clearanceUrl: "https://example.com",
    },
    downloads: [
      {
        downloadId: "full",
        variant: "full",
        label: "Full",
        format: "wav",
        directUrl: "/music/audio/midnight-commute.wav",
      },
    ],
  },
  {
    id: "sample-9",
    slug: "sample-9",
    title: "サンプル音源9",
    artist: "Music Library",
    albumArtSrc: "/music/art/paper-skies.svg",
    audioSrc: "/music/audio/paper-skies.wav",
    description: "This is a sample track for template demonstration.",
    bpm: 94,
    tags: ["tag-9"],
    license: {
      licenseId: "sample",
      requiresAgreement: false,
      note: "Template sample license note. Replace this with your own policy.",
      clearanceUrl: "https://example.com",
    },
    downloads: [
      {
        downloadId: "full",
        variant: "full",
        label: "Full",
        format: "wav",
        directUrl: "/music/audio/paper-skies.wav",
      },
    ],
  },
  {
    id: "sample-10",
    slug: "sample-10",
    title: "サンプル音源10",
    artist: "Music Library",
    albumArtSrc: "/music/art/neon-rain.svg",
    audioSrc: "/music/audio/neon-rain.wav",
    description: "This is a sample track for template demonstration.",
    bpm: 105,
    tags: ["tag-10"],
    license: {
      licenseId: "sample",
      requiresAgreement: true,
      note: "Template sample license note. Replace this with your own policy.",
      clearanceUrl: "https://example.com",
    },
    downloads: [
      {
        downloadId: "full",
        variant: "full",
        label: "Full",
        format: "wav",
        directUrl: "/music/audio/neon-rain.wav",
      },
    ],
  },
  {
    id: "sample-11",
    slug: "sample-11",
    title: "サンプル音源11",
    artist: "Music Library",
    albumArtSrc: "/music/art/calm-current.svg",
    audioSrc: "/music/audio/calm-current.wav",
    description: "This is a sample track for template demonstration.",
    bpm: 76,
    tags: ["tag-11"],
    license: {
      licenseId: "sample",
      requiresAgreement: false,
      note: "Template sample license note. Replace this with your own policy.",
      clearanceUrl: "https://example.com",
    },
    downloads: [
      {
        downloadId: "full",
        variant: "full",
        label: "Full",
        format: "wav",
        directUrl: "/music/audio/calm-current.wav",
      },
    ],
  },
  {
    id: "sample-12",
    slug: "sample-12",
    title: "サンプル音源12",
    artist: "Music Library",
    albumArtSrc: "/music/art/silver-steps.svg",
    audioSrc: "/music/audio/silver-steps.wav",
    description: "This is a sample track for template demonstration.",
    bpm: 98,
    tags: ["tag-12"],
    license: {
      licenseId: "sample",
      requiresAgreement: true,
      note: "Template sample license note. Replace this with your own policy.",
      clearanceUrl: "https://example.com",
    },
    downloads: [
      {
        downloadId: "full",
        variant: "full",
        label: "Full",
        format: "wav",
        directUrl: "/music/audio/silver-steps.wav",
      },
    ],
  },
  {
    id: "sample-13",
    slug: "sample-13",
    title: "サンプル音源13",
    artist: "Music Library",
    albumArtSrc: "/music/art/aurora-drift.svg",
    audioSrc: "/music/audio/aurora-drift.wav",
    description: "This is a sample track for template demonstration.",
    bpm: 80,
    tags: ["tag-13"],
    license: {
      licenseId: "sample",
      requiresAgreement: false,
      note: "Template sample license note. Replace this with your own policy.",
      clearanceUrl: "https://example.com",
    },
    downloads: [
      {
        downloadId: "full",
        variant: "full",
        label: "Full",
        format: "wav",
        directUrl: "/music/audio/aurora-drift.wav",
      },
    ],
  },
  {
    id: "sample-14",
    slug: "sample-14",
    title: "サンプル音源14",
    artist: "Music Library",
    albumArtSrc: "/music/art/midnight-commute.svg",
    audioSrc: "/music/audio/midnight-commute.wav",
    description: "This is a sample track for template demonstration.",
    bpm: 92,
    tags: ["tag-14"],
    license: {
      licenseId: "sample",
      requiresAgreement: true,
      note: "Template sample license note. Replace this with your own policy.",
      clearanceUrl: "https://example.com",
    },
    downloads: [
      {
        downloadId: "full",
        variant: "full",
        label: "Full",
        format: "wav",
        directUrl: "/music/audio/midnight-commute.wav",
      },
    ],
  },
  {
    id: "sample-15",
    slug: "sample-15",
    title: "サンプル音源15",
    artist: "Music Library",
    albumArtSrc: "/music/art/paper-skies.svg",
    audioSrc: "/music/audio/paper-skies.wav",
    description: "This is a sample track for template demonstration.",
    bpm: 86,
    tags: ["tag-15"],
    license: {
      licenseId: "sample",
      requiresAgreement: false,
      note: "Template sample license note. Replace this with your own policy.",
      clearanceUrl: "https://example.com",
    },
    downloads: [
      {
        downloadId: "full",
        variant: "full",
        label: "Full",
        format: "wav",
        directUrl: "/music/audio/paper-skies.wav",
      },
    ],
  },
];
